# Generated by Django 4.1.2 on 2022-10-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boats',
            new_name='Boat',
        ),
        migrations.RenameModel(
            old_name='BoatPics',
            new_name='BoatPic',
        ),
    ]
