# Generated by Django 4.1.2 on 2022-10-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_app', '0004_alter_boat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
