# Generated by Django 4.1.2 on 2022-10-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_app', '0005_boat_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatpic',
            name='img',
            field=models.ImageField(default='test', upload_to='images'),
            preserve_default=False,
        ),
    ]
