# Generated by Django 4.1.2 on 2022-10-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats_app', '0006_boatpic_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatpic',
            name='name',
        ),
    ]
